version: "3.1"
services:
  php-fpm:
    build: .
    container_name: cake2-webserver
    volumes:
    - ./:/var/www/html
    depends_on:
      - mysql
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/webroot/
    ports:
      - "8081:80"
  mysql:
    image: mysql:5.6
    container_name: cake2-mysql
    working_dir: /app
    volumes:
      # - .:/app
      # - ./tmp/data/mysql_db:/var/lib/mysql
      - 'mysql:/var/lib/mysql'
      - ./docker/db/backup/files:/docker-entrypoint-initdb.d
    env_file:
      - mysql.env
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'
    ports:
      - "3306:3306"

volumes:
  mysql:
      driver: local
